// app/api/generate-poster-background/route.ts
//
// Generates a decorative background image (no people, no faces — purely
// pattern/art/texture) from a text prompt, using Pollinations.ai — a
// genuinely free, no-API-key image generation endpoint. Uploads the
// result to storage and returns its public URL. This URL then gets
// passed into composePolaroidPoster as the base layer — the real
// uploaded photo is still composited by code afterward, never touched
// or regenerated by any AI model.
//
// (Switched from Gemini's image models after confirming they don't have
// a reliably free API tier — gemini-3-pro-image-preview returned a
// hard 0 free quota, and gemini-2.5-flash-image-preview isn't even
// available on this API version. Pollinations has no such limits.)

import { NextResponse } from "next/server";
import { createCanvas, loadImage } from "@napi-rs/canvas";
import { requireUser } from "@/lib/requireUser";
import { supabaseAdmin } from "@/lib/supabaseAdmin";

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchWithRetry(url: string, maxRetries = 2) {
  let lastError: unknown;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`Pollinations returned ${res.status}`);
      return res;
    } catch (err) {
      lastError = err;
      if (attempt === maxRetries) throw err;
      await sleep(1000 * (attempt + 1));
    }
  }
  throw lastError;
}

export async function POST(req: Request) {
  const { user, error: authError } = await requireUser(req);
  if (!user) {
    return NextResponse.json({ error: authError }, { status: 401 });
  }

  const { prompt } = await req.json();
  if (!prompt || typeof prompt !== "string") {
    return NextResponse.json({ error: "Missing prompt" }, { status: 400 });
  }

  // Steer away from generating any people — this is a background layer
  // only, the real photo goes on top separately afterward.
  const fullPrompt = `decorative birthday card background, ${prompt}, no people, no faces, no human figures, pure pattern texture abstract shapes or scenery only, soft and not too busy, portrait orientation`;

  // A random seed avoids Pollinations serving a cached identical image
  // for the same prompt text on a repeat click. Requesting extra height
  // (1300 instead of 1200) gives room to crop off the watermark strip
  // below without shrinking the final usable image.
  const seed = Math.floor(Math.random() * 1_000_000);
  const requestHeight = 1300;
  const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(
    fullPrompt,
  )}?width=800&height=${requestHeight}&model=flux&nologo=true&private=true&seed=${seed}`;

  try {
    const imageRes = await fetchWithRetry(url);
    const rawBuffer = Buffer.from(await imageRes.arrayBuffer());

    // Pollinations' nologo flag doesn't always suppress the watermark, so
    // crop the bottom ~8% off unconditionally — cheap insurance either
    // way, since composePolaroidPoster cover-fit-scales this background
    // to fill the poster canvas regardless of its exact dimensions.
    const sourceImg = await loadImage(rawBuffer);
    const cropRatio = 0.92;
    const croppedHeight = Math.floor(sourceImg.height * cropRatio);
    const cropCanvas = createCanvas(sourceImg.width, croppedHeight);
    const cropCtx = cropCanvas.getContext("2d");
    cropCtx.drawImage(
      sourceImg,
      0,
      0,
      sourceImg.width,
      croppedHeight,
      0,
      0,
      sourceImg.width,
      croppedHeight,
    );
    const imageBuffer = cropCanvas.toBuffer("image/jpeg");

    const storagePath = `backgrounds/${crypto.randomUUID()}.jpg`;
    const { error: uploadError } = await supabaseAdmin.storage
      .from("wish-photos")
      .upload(storagePath, imageBuffer, {
        contentType: "image/jpeg",
        cacheControl: "31536000",
      });
    if (uploadError) throw new Error(uploadError.message);

    const { data } = supabaseAdmin.storage
      .from("wish-photos")
      .getPublicUrl(storagePath);

    return NextResponse.json({ backgroundUrl: data.publicUrl });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
